name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build Swift Application
      run: |
        swiftc PingMonitor.swift -o PingMonitor \
          -target arm64-apple-macos13.0 \
          -Osize

    - name: Create App Bundle
      run: |
        mkdir -p PingMonitor.app/Contents/MacOS
        mkdir -p PingMonitor.app/Contents/Resources
        cp PingMonitor PingMonitor.app/Contents/MacOS/

        cat > PingMonitor.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>PingMonitor</string>
            <key>CFBundleIdentifier</key>
            <string>com.pingmonitor.app</string>
            <key>CFBundleName</key>
            <string>PingMonitor</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.0</string>
            <key>LSMinimumSystemVersion</key>
            <string>13.0</string>
            <key>LSUIElement</key>
            <true/>
        </dict>
        </plist>
        EOF

    - name: Create DMG
      run: |
        mkdir dmg_temp
        cp -R PingMonitor.app dmg_temp/
        ln -s /Applications dmg_temp/Applications

        hdiutil create -volname "PingMonitor" \
          -srcfolder dmg_temp \
          -ov -format UDZO \
          PingMonitor.dmg

    - name: Create ZIP
      run: |
        zip -r PingMonitor.zip PingMonitor.app

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: PingMonitor-macOS
        path: |
          PingMonitor.dmg
          PingMonitor.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          PingMonitor.dmg
          PingMonitor.zip
        draft: false
        prerelease: false