name: Signed Release Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: '1.1.0'

env:
  PRODUCT_NAME: "PingMonitor"
  BUNDLE_ID: "com.pingmonitor.app"

jobs:
  build-signed-release:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get version
      id: version
      run: |
        echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT

    - name: Build Universal Binary
      run: |
        # Build for ARM64
        swiftc PingMonitor.swift -o PingMonitor-arm64 \
          -target arm64-apple-macos13.0 \
          -Osize

        # Build for x86_64
        swiftc PingMonitor.swift -o PingMonitor-x86_64 \
          -target x86_64-apple-macos13.0 \
          -Osize

        # Create universal binary
        lipo -create -output PingMonitor PingMonitor-arm64 PingMonitor-x86_64

        # Verify architectures
        lipo -archs PingMonitor

    - name: Create App Bundle
      run: |
        # Create app bundle structure
        mkdir -p "$PRODUCT_NAME.app/Contents/MacOS"
        mkdir -p "$PRODUCT_NAME.app/Contents/Resources"

        # Copy binary
        cp PingMonitor "$PRODUCT_NAME.app/Contents/MacOS/"

        # Create Info.plist
        cat > "$PRODUCT_NAME.app/Contents/Info.plist" << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleDevelopmentRegion</key>
            <string>en</string>
            <key>CFBundleExecutable</key>
            <string>$PRODUCT_NAME</string>
            <key>CFBundleIdentifier</key>
            <string>$BUNDLE_ID</string>
            <key>CFBundleName</key>
            <string>$PRODUCT_NAME</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>${{ steps.version.outputs.VERSION }}</string>
            <key>CFBundleVersion</key>
            <string>${{ steps.version.outputs.VERSION }}</string>
            <key>LSMinimumSystemVersion</key>
            <string>13.0</string>
            <key>LSUIElement</key>
            <true/>
            <key>NSPrincipalClass</key>
            <string>NSApplication</string>
            <key>NSHighResolutionCapable</key>
            <true/>
            <key>NSSupportsAutomaticGraphicsSwitching</key>
            <true/>
            <key>NSRequiresAquaSystemAppearance</key>
            <false/>
        </dict>
        </plist>
        EOF

    - name: Test Build
      run: |
        echo "✅ Build completed successfully!"
        ls -la "$PRODUCT_NAME.app/Contents/MacOS/"