name: Test Lando Signing

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.3.0'

env:
  PRODUCT_NAME: "PingMonitor"

jobs:
  test-signing:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Simple Binary
      run: |
        swiftc PingMonitor.swift -o PingMonitor
        mkdir -p "$PRODUCT_NAME.app/Contents/MacOS"
        cp PingMonitor "$PRODUCT_NAME.app/Contents/MacOS/"

        cat > "$PRODUCT_NAME.app/Contents/Info.plist" << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>PingMonitor</string>
            <key>CFBundleIdentifier</key>
            <string>com.pingmonitor.app</string>
            <key>CFBundleName</key>
            <string>PingMonitor</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>1.3.0</string>
            <key>CFBundleVersion</key>
            <string>1.3.0</string>
            <key>LSUIElement</key>
            <true/>
        </dict>
        </plist>
        EOF

    - name: Debug File Structure
      run: |
        echo "Current directory:"
        pwd
        echo "Files in current directory:"
        ls -la
        echo "Looking for PingMonitor.app:"
        find . -name "*.app" -type d

    - name: Test Lando Code Sign
      uses: lando/code-sign-action@v2
      with:
        file: ./PingMonitor.app
        certificate-data: ${{ secrets.APPLE_CERTIFICATE_P12 }}
        certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
        apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
        options: --deep --force --verbose --options runtime

    - name: Verify Signature
      run: |
        codesign --verify --verbose=2 "$PRODUCT_NAME.app"
        echo "✅ Lando signing successful!"

    - name: Upload Test Result
      uses: actions/upload-artifact@v4
      with:
        name: lando-signed-test
        path: ${{ env.PRODUCT_NAME }}.app