name: Test Official

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.2.0'

env:
  PRODUCT_NAME: "PingMonitor"

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test
      run: |
        echo "Testing workflow syntax"
        echo "Product: $PRODUCT_NAME"
        echo "Version: ${{ github.event.inputs.version }}"